name: Build ZuppiCalling Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Chocolatey and MSYS2
      run: |
        choco install -y msys2
        echo "C:\tools\msys64\usr\bin" >> $GITHUB_ENV
        echo "C:\tools\msys64\mingw64\bin" >> $GITHUB_ENV

    - name: Update MSYS2 and Install Dependencies
      shell: bash
      run: |
        export PATH=/c/tools/msys64/usr/bin:/c/tools/msys64/mingw64/bin:$PATH
        pacman --noconfirm -Syuu
        pacman --noconfirm -S base-devel mingw-w64-x86_64-toolchain \
            mingw-w64-x86_64-speex mingw-w64-x86_64-libsrtp mingw-w64-x86_64-libwinpthread

    - name: Create Custom Configuration
      run: |
        echo "#define PJ_HAS_NETINET_IP_H 0" > pjproject/pjlib/include/pj/config_site.h
        echo "#define PJ_THREAD_SET_STACK_SIZE 0" >> pjproject/pjlib/include/pj/config_site.h
        echo "#define PJ_THREAD_ALLOCATE_STACK 0" >> pjproject/pjlib/include/pj/config_site.h
        echo "#define PJ_BLOCKING_ERROR_VAL WSAEWOULDBLOCK" >> pjproject/pjlib/include/pj/config_site.h
        echo "#define PJ_BLOCKING_CONNECT_ERROR_VAL WSAEWOULDBLOCK" >> pjproject/pjlib/include/pj/config_site.h

    - name: Clone and Configure PJSIP
      shell: bash
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        curl -o config.guess https://git.savannah.gnu.org/cgit/config.git/plain/config.guess
        curl -o config.sub https://git.savannah.gnu.org/cgit/config.git/plain/config.sub
        ./aconfigure \
          --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --prefix=$(pwd)/install \
          CFLAGS="-I/mingw64/include -I$(pwd)/pjlib/include" \
          LDFLAGS="-L/mingw64/lib"

    - name: Build Dependencies and PJSIP
      shell: bash
      run: |
        cd pjproject
        make dep -j$(nproc) || (cat config.log && exit 1)
        make -j$(nproc) || (cat config.log && exit 1)
        make install

    - name: Build ZuppiCalling
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
