name: Build ZuppiCalling

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install MSYS2
      run: |
        choco install -y msys2
        echo "C:\tools\msys64\usr\bin" >> $env:GITHUB_PATH
        echo "C:\tools\msys64\mingw64\bin" >> $env:GITHUB_PATH
        echo "C:\tools\msys64\mingw32\bin" >> $env:GITHUB_PATH
        refreshenv

    - name: Update MSYS2 and Install Dependencies
      run: |
        C:\tools\msys64\usr\bin\bash -lc "pacman --noconfirm -Syuu"
        C:\tools\msys64\usr\bin\bash -lc "pacman --noconfirm -S base-devel mingw-w64-x86_64-toolchain"

    - name: Build PJSIP
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        curl -L -o config.guess https://git.savannah.gnu.org/cgit/config.git/plain/config.guess
        curl -L -o config.sub https://git.savannah.gnu.org/cgit/config.git/plain/config.sub
        C:\tools\msys64\usr\bin\bash -lc "./configure --prefix=$(pwd)/install --disable-samples"
        C:\tools\msys64\usr\bin\bash -lc "make && make install"

    - name: Install JSON Library
      run: |
        git clone https://github.com/nlohmann/json.git lib/json

    - name: Build ZuppiCalling
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
