name: Build ZuppiCalling

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install MSYS2
      run: choco install -y msys2

    - name: Add MSYS2 to PATH
      shell: bash
      run: |
        echo "C:\\tools\\msys64\\usr\\bin" >> $GITHUB_PATH
        echo "C:\\tools\\msys64\\mingw64\\bin" >> $GITHUB_PATH
        echo "C:\\tools\\msys64\\mingw32\\bin" >> $GITHUB_PATH

    - name: Initialize MSYS2
      shell: bash
      run: |
        export PATH=/c/tools/msys64/usr/bin:/c/tools/msys64/mingw64/bin:$PATH
        pacman -Syu --noconfirm
        pacman -S --noconfirm base-devel mingw-w64-x86_64-toolchain

    - name: Install PJSIP
      shell: bash
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        curl -o config.guess http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
        curl -o config.sub http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
        ./configure --prefix=$(pwd)/install
        make
        make install

    - name: Install JSON Library
      run: |
        git clone https://github.com/nlohmann/json.git lib/json

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
