name: Build ZuppiCalling Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install MSYS2 using Chocolatey
    - name: Install MSYS2 via Chocolatey
      run: |
        choco install -y msys2

    # Step 3: Manually Add MSYS2 Paths to the Environment
    - name: Add MSYS2 Paths to Environment
      run: |
        echo "C:\\tools\\msys64\\usr\\bin" >> $GITHUB_ENV
        echo "C:\\tools\\msys64\\mingw64\\bin" >> $GITHUB_ENV

    # Step 4: Update MSYS2 and Install Build Dependencies
    - name: Update MSYS2 and Install Dependencies
      shell: bash
      run: |
        export PATH=/c/tools/msys64/usr/bin:/c/tools/msys64/mingw64/bin:$PATH
        pacman --noconfirm -Syuu
        pacman --noconfirm -S base-devel mingw-w64-x86_64-toolchain

    # Step 5: Clone PJSIP Repository and Update Config Files
    - name: Clone and Configure PJSIP
      shell: bash
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        curl -o config.guess https://git.savannah.gnu.org/cgit/config.git/plain/config.guess
        curl -o config.sub https://git.savannah.gnu.org/cgit/config.git/plain/config.sub

    # Step 6: Build PJSIP
    - name: Build PJSIP
      shell: bash
      run: |
        cd pjproject
        ./configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --prefix=$(pwd)/install \
            --disable-samples \
            CFLAGS="-I/mingw64/include" \
            LDFLAGS="-L/mingw64/lib"
        make -j$(nproc) && make install

    # Step 7: Configure and Build ZuppiCalling
    - name: Configure and Build ZuppiCalling
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    # Step 8: Upload Built Executable
    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
