name: Build ZuppiCalling Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Chocolatey and MSYS2
    - name: Install Chocolatey and MSYS2
      run: |
        choco install -y msys2
        refreshenv

    # Step 3: Add MSYS2 to PATH
    - name: Configure MSYS2 PATH
      run: |
        echo "C:\tools\msys64\usr\bin" >> $GITHUB_ENV
        echo "C:\tools\msys64\mingw64\bin" >> $GITHUB_ENV

    # Step 4: Update MSYS2 Packages
    - name: Update MSYS2 Packages
      shell: bash
      run: |
        export PATH=/c/tools/msys64/usr/bin:/c/tools/msys64/mingw64/bin:$PATH
        pacman --noconfirm -Syuu

    # Step 5: Install Build Dependencies
    - name: Install Dependencies
      shell: bash
      run: |
        pacman --noconfirm -S base-devel mingw-w64-x86_64-toolchain

    # Step 6: Clone and Configure PJSIP
    - name: Clone and Configure PJSIP
      shell: bash
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        curl -o config.guess https://git.savannah.gnu.org/cgit/config.git/plain/config.guess
        curl -o config.sub https://git.savannah.gnu.org/cgit/config.git/plain/config.sub

    # Step 7: Build PJSIP
    - name: Build PJSIP
      shell: bash
      run: |
        cd pjproject
        ./configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --prefix=$(pwd)/install \
            --disable-samples \
            CFLAGS="-I/mingw64/include" \
            LDFLAGS="-L/mingw64/lib"
        make && make install

    # Step 8: Configure and Build ZuppiCalling
    - name: Configure and Build ZuppiCalling
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    # Step 9: Upload Built Executable
    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
