name: Build ZuppiCalling Executable

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install dependencies with Chocolatey
    - name: Install Dependencies
      run: |
        choco install -y mingw
        choco install -y msys2

    # Step 3: Update PATH for MSYS2 and MinGW
    - name: Update PATH
      run: |
        echo "C:\tools\msys64\usr\bin;C:\tools\msys64\mingw64\bin;%PATH%" > $env:GITHUB_PATH

    # Step 4: Clone and update PJSIP
    - name: Clone and Update PJSIP
      shell: bash
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        curl -o config.guess https://git.savannah.gnu.org/cgit/config.git/plain/config.guess
        curl -o config.sub https://git.savannah.gnu.org/cgit/config.git/plain/config.sub

    # Step 5: Build PJSIP
    - name: Build PJSIP
      shell: bash
      run: |
        cd pjproject
        ./configure --host=x86_64-w64-mingw32 --build=x86_64-w64-mingw32 --prefix=$(pwd)/install \
            --disable-samples \
            CFLAGS="-I/mingw64/include" \
            LDFLAGS="-L/mingw64/lib"
        make && make install

    # Step 6: Configure and Build ZuppiCalling
    - name: Configure and Build ZuppiCalling
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    # Step 7: Upload Built Executable
    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
