name: Build ZuppiCalling

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install MSYS2
      run: |
        choco install -y msys2
        echo "Adding MSYS2 paths to the environment."
        echo "C:\\tools\\msys64\\usr\\bin" >> $GITHUB_ENV
        echo "C:\\tools\\msys64\\mingw64\\bin" >> $GITHUB_ENV
        echo "C:\\tools\\msys64\\mingw32\\bin" >> $GITHUB_ENV
        echo "C:\\tools\\msys64\\ucrt64\\bin" >> $GITHUB_ENV
        echo "PATH updated with MSYS2 paths."

    - name: Initialize MSYS2
      shell: bash
      run: |
        echo "Starting MSYS2 initialization."
        pacman --noconfirm -Syuu
        pacman --noconfirm -S base-devel mingw-w64-x86_64-toolchain
        echo "MSYS2 initialization completed."

    - name: Clone and Build PJSIP
      shell: bash
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        curl -o config.guess http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
        curl -o config.sub http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD
        chmod +x config.guess config.sub
        ./configure --prefix=$(pwd)/install
        make
        make install

    - name: Install JSON Library
      run: |
        git clone https://github.com/nlohmann/json.git lib/json

    - name: Build ZuppiCalling
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
