name: Build ZuppiCalling

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install MSYS2
      run: |
        choco install -y msys2
        echo "C:\\tools\\msys64\\usr\\bin" >> $GITHUB_ENV
        echo "C:\\tools\\msys64\\mingw64\\bin" >> $GITHUB_ENV
        echo "C:\\tools\\msys64\\mingw32\\bin" >> $GITHUB_ENV
        echo "C:\\tools\\msys64\\ucrt64\\bin" >> $GITHUB_ENV
        echo "C:\\tools\\msys64\\clang64\\bin" >> $GITHUB_ENV

    - name: Initialize MSYS2
      shell: bash
      run: |
        export PATH="/c/tools/msys64/usr/bin:/c/tools/msys64/mingw64/bin:/c/tools/msys64/mingw32/bin:$PATH"
        pacman --noconfirm -Syuu
        pacman --noconfirm -S base-devel mingw-w64-x86_64-toolchain

    - name: Build PJSIP
      shell: bash
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        curl -L -o config.guess https://git.savannah.gnu.org/cgit/config.git/plain/config.guess
        curl -L -o config.sub https://git.savannah.gnu.org/cgit/config.git/plain/config.sub
        chmod +x config.guess config.sub
        ./configure --prefix=$(pwd)/install --disable-samples
        make
        make install

    - name: Install JSON Library
      run: |
        git clone https://github.com/nlohmann/json.git lib/json

    - name: Build ZuppiCalling
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
