name: Build ZuppiCalling

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set Up CMake
      uses: lukka/get-cmake@v3

    - name: Install Dependencies
      run: |
        choco install -y visualstudio2022buildtools
        choco install -y visualstudio2022-workload-vctools

    - name: Install PJSIP
      run: |
        git clone https://github.com/pjsip/pjproject.git
        cd pjproject
        cmake . -B build -DCMAKE_INSTALL_PREFIX=./install
        cmake --build build --config Release
        cmake --install build

    - name: Install JSON Library
      run: |
        git clone https://github.com/nlohmann/json.git lib/json

    - name: Build Project
      run: |
        mkdir build
        cd build
        cmake -A x64 -DPJSIP_INCLUDE_DIR=../pjproject/install/include -DPJSIP_LIBRARY=../pjproject/install/lib ..
        cmake --build . --config Release

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: ZuppiCalling-Executable
        path: build/Release/ZuppiCalling.exe
